baseurl = "http://bhberson.github.io/muskegon-risers/"
languageCode = "en-us"
title = "Muskegon Risers"
googleanalytics = "XX-00000000-0"
copyright = "© 2016 Muskegon Risers Soccer Club. All Rights Reserved"
disableRSS = true

[params]
  keywords = "pro soccer, muskegon, soccer club, soccer, grand haven, whitehall, NPSL, PDL"
  googleverification = "FGOvBqPlJa4NNhTN58o7Izde6oJ6Gx8Lk2au7QKWY08"
  googleremarket = "929250372"
  snipcart = "Zjc3YWZlOWYtM2M5MC00YzdlLThlMzMtOWIzODIzNDIzMmQ2NjM1ODkyMDQ2NDk4ODYyNzYw"
  twitter = "RisersSC"
  twitterwidgetID = "696555488402485248"
  facebook = "MuskegonRisersSC"
  fbpageID = "666777940040738"
  fbpixel = "1722595211311008"
  instagram = "riserssc"
  phone = "(231) 123-4567"
  address1 = "W Western Ave"
  address2 = "Muskegon, MI 49440"
  addresshelp = "Just East of Exit 114 off U.S. 31."
  googlemaps = "https://goo.gl/maps/iYGcUDE1nVu"
  email = "riserssc@gmail.com"
