baseurl = "https://muskegonrisers.com/"
languageCode = "en-us"
title = "Muskegon Risers"
googleanalytics = "UA-74374211-1"
copyright = "© 2016 Muskegon Risers Soccer Club. All Rights Reserved"
disableKinds=["RSS"]

[params]
  description = "Muskegon Risers SC strives to represent the spirit of our area's people in past, present and future tense."
  keywords = "pro soccer, muskegon, soccer club, soccer, grand haven, whitehall, NPSL, PDL, watch muskegon"
  googleverification = "FGOvBqPlJa4NNhTN58o7Izde6oJ6Gx8Lk2au7QKWY08"
  googleremarket = "929250372"
  snipcart = "YmIwNWQ2ZGUtNTZmOC00YWFjLTg3ODgtZWRlMTQ0YTk2YTQ4NjM1OTE2OTQ0NjkwNTExMTAx"
  twitter = "RisersSC"
  twitterremarket = true
  facebook = "MuskegonRisersSC"
  fbpageID = "666777940040738"
  fbpixel = "1722595211311008"
  instagram = "riserssc"
  email = "riserssc@gmail.com"
  notification = "<i class=\"fa fa-soccer-ball-o\"></i> Have you saved your seat?!? Grab your 2017 Season Tickets <a href=\"store/season-ticket-package/\">now</a>! <i class=\"fa fa-soccer-ball-o\"></i>"
