baseurl = "http://bhberson.github.io/muskegon-risers/"
languageCode = "en-us"
title = "Muskegon Risers"
googleanalytics = "UA-74374211-1"
copyright = "© 2016 Muskegon Risers Soccer Club. All Rights Reserved"
disableRSS = true

[params]
  keywords = "pro soccer, muskegon, soccer club, soccer, grand haven, whitehall, NPSL, PDL"
  googleverification = "FGOvBqPlJa4NNhTN58o7Izde6oJ6Gx8Lk2au7QKWY08"
  googleremarket = "929250372"
  snipcart = "MGI5ODI1ZjItYmFkMi00ZGVjLWE4YWYtMzlmMmE5MGJlZmFlNjM1ODg1Nzc0Mzc1OTAyMzQz"
  twitter = "RisersSC"
  twitterremarket = true
  facebook = "MuskegonRisersSC"
  fbpageID = "666777940040738"
  fbpixel = "1722595211311008"
  instagram = "riserssc"
  email = "riserssc@gmail.com"
  notification = "<i class=\"fa fa-soccer-ball-o\"></i> Have you saved your seat?!? Grab your 2016 Season Tickets <a href=\"store/season-ticket-package/\">now</a>! <i class=\"fa fa-soccer-ball-o\"></i>"
